/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserModal: typeof import('./src/components/UserModal.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
  }
}
